import{YoyoVoice}from'./audio';import{createYoyoState,releaseYoyo,requestReturn,stepYoyo,type YoyoState}from'./physics';import{styles}from'./styles';
const TAG='retro-yoyo',STEP=1/120,Base=(typeof HTMLElement==='undefined'?class{}:HTMLElement)as typeof HTMLElement;
export interface YoyoOptions{sound?:boolean;stringLength?:number}
export class RetroYoyoElement extends Base{private readonly canvas=document.createElement('canvas');private readonly context=this.canvas.getContext('2d')!;private readonly voice=new YoyoVoice();private stateValue:YoyoState=createYoyoState(640,620);private pointer={held:false,x:0,y:0};private resizeObserver?:ResizeObserver;private frame=0;private previous=0;private accumulator=0;private impact=0;private soundEnabled=true;
constructor(){super();const root=this.attachShadow({mode:'open'}),style=document.createElement('style'),hint=document.createElement('p');style.textContent=styles;hint.className='hint';hint.textContent='拖动手指甩线 · 睡眠后点“收线”';this.canvas.setAttribute('aria-label','可甩动的网页悠悠球');root.append(style,this.canvas,hint);}get state():Readonly<YoyoState>{return this.stateValue}get playbackState(){return this.voice.playbackState}
connectedCallback(){this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this);this.canvas.addEventListener('pointerdown',this.down);this.canvas.addEventListener('pointermove',this.move);this.canvas.addEventListener('pointerup',this.up);this.canvas.addEventListener('pointercancel',this.up);this.resize();this.frame=requestAnimationFrame(this.tick)}disconnectedCallback(){this.destroy()}
configure(options:YoyoOptions){if(typeof options.sound==='boolean')this.soundEnabled=options.sound;if(Number.isFinite(options.stringLength)){this.stateValue.maxStringLength=Math.min(310,Math.max(100,options.stringLength!));this.stateValue.stringLength=this.stateValue.maxStringLength;}}
async unlockSound(){return this.soundEnabled?this.voice.unlock():false}return=()=>requestReturn(this.stateValue);release=()=>releaseYoyo(this.stateValue);reset=()=>{this.stateValue=createYoyoState(this.clientWidth||640,this.clientHeight||620);this.impact=0};destroy(){cancelAnimationFrame(this.frame);this.resizeObserver?.disconnect();this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointermove',this.move);this.canvas.removeEventListener('pointerup',this.up);this.canvas.removeEventListener('pointercancel',this.up);this.voice.destroy()}
private resize(){const d=Math.min(2,window.devicePixelRatio||1),w=Math.max(1,Math.round(this.clientWidth*d)),h=Math.max(1,Math.round(this.clientHeight*d));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}}
private point(e:PointerEvent){const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}private down=(e:PointerEvent)=>{this.pointer={held:true,...this.point(e)};this.canvas.setPointerCapture(e.pointerId)};private move=(e:PointerEvent)=>{if(this.pointer.held)Object.assign(this.pointer,this.point(e))};private up=(e:PointerEvent)=>{this.pointer.held=false;if(this.canvas.hasPointerCapture(e.pointerId))this.canvas.releasePointerCapture(e.pointerId)};
private tick=(time:number)=>{const elapsed=Math.min(.05,Math.max(0,(time-this.previous)/1000));this.previous=time;this.accumulator+=elapsed;const bounds={width:this.clientWidth||640,height:this.clientHeight||620};let n=0;while(this.accumulator>=STEP&&n++<8){stepYoyo(this.stateValue,this.pointer,STEP,bounds);this.accumulator-=STEP}if(this.impact!==this.stateValue.impactSerial){this.impact=this.stateValue.impactSerial;this.voice.strike(this.stateValue.impactSpeed)}this.voice.update(this.stateValue.disc.angularVelocity,this.stateValue.taut,this.stateValue.phase);this.draw(bounds.width,bounds.height);this.frame=requestAnimationFrame(this.tick)};
private draw(width:number,height:number){const d=Math.min(2,window.devicePixelRatio||1),c=this.context,s=this.stateValue;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,width,height);const bg=c.createLinearGradient(0,0,0,height);bg.addColorStop(0,'#d9e2dc');bg.addColorStop(1,'#8eb0b2');c.fillStyle=bg;c.fillRect(0,0,width,height);c.strokeStyle='rgba(255,255,255,.16)';for(let y=20;y<height;y+=26){c.beginPath();c.moveTo(0,y);c.lineTo(width,y);c.stroke()}c.strokeStyle='#ede0bd';c.lineWidth=2;c.beginPath();c.moveTo(s.hand.x,s.hand.y);c.lineTo(s.disc.x,s.disc.y);c.stroke();c.fillStyle='#2d4d59';c.beginPath();c.arc(s.hand.x,s.hand.y,9,0,Math.PI*2);c.fill();c.save();c.translate(s.disc.x,s.disc.y);c.rotate(s.disc.angle);c.fillStyle='#b83231';c.strokeStyle='#5f2026';c.lineWidth=4;c.beginPath();c.ellipse(0,0,s.discRadius,s.discRadius*.84,0,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#e8b85e';c.fillRect(-s.discRadius, -4,s.discRadius*2,8);c.fillStyle='#302d2a';c.beginPath();c.arc(0,0,5,0,Math.PI*2);c.fill();c.strokeStyle='rgba(255,255,255,.5)';c.lineWidth=2;c.beginPath();c.moveTo(-15,-12);c.lineTo(15,12);c.stroke();c.restore();c.fillStyle='#274957';c.font='700 10px system-ui';c.fillText(s.phase.toUpperCase(),18,25)} }
export function defineYoyo(tag=TAG){if(typeof customElements!=='undefined'&&!customElements.get(tag))customElements.define(tag,RetroYoyoElement)}export function mountYoyo(target:Element,options:YoyoOptions={}){defineYoyo();const e=document.createElement(TAG)as RetroYoyoElement;e.configure(options);target.append(e);return e}
